version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_controlaccess
    environment:
      MYSQL_ROOT_PASSWORD: Kraus@8770
      MYSQL_DATABASE: controlaccess_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data: